# Generated by Django 3.0.8 on 2020-07-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_title', models.CharField(max_length=100, verbose_name='Название статьи')),
                ('art_text', models.TextField(verbose_name='Текст статьи')),
                ('public_date', models.DateTimeField(verbose_name='Дата публикации')),
                ('art_pic', models.CharField(max_length=200, verbose_name='Путь к картинке на сервере')),
            ],
        ),
    ]
