# Generated by Django 3.0.8 on 2020-07-31 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200731_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='public_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 20, 30, 43, 916093), verbose_name='Дата публикации'),
        ),
    ]
