# Generated by Django 3.0.8 on 2020-07-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20200731_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='public_date',
            field=models.DateTimeField(default='2020-07-31 20:34:26.287299', verbose_name='Дата публикации'),
        ),
    ]
