# Generated by Django 3.0.8 on 2020-07-31 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20200731_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='art_pic',
            field=models.CharField(max_length=200, verbose_name='Путь к картинке на сервере'),
        ),
    ]
