# Generated by Django 3.0.8 on 2020-07-31 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20200731_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='art_description',
            field=models.TextField(verbose_name='Описание статьи'),
        ),
    ]
