# Generated by Django 3.0.8 on 2020-08-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_auto_20200731_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='art_title',
            field=models.CharField(default='', max_length=200, verbose_name='Название статьи'),
        ),
    ]
